---
ansible_user: root
ansible_host: z.mir3g.1984.run

root_password: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/root') }}"

cjdns_private_key: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=private') }}"
cjdns_public_key: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=public') }}"
cjdns_ipv6: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=ipv6') }}"
cjdns_admin_password: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=admin_password') }}"
cjdns_authorizedPasswords:
  default-login: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=authorized_password_default_login') }}"
  private: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=authorized_password_private') }}"

cjdns_udp_peers_self: []

cjdns_udp_peers: []
