---
cjdns_private_key: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=private') }}"
cjdns_public_key: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=public') }}"
cjdns_ipv6: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=ipv6') }}"
cjdns_admin_password: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=admin_password') }}"
cjdns_authorizedPasswords:
  default-login: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=authorized_password_default_login') }}"
  private: "{{ lookup('passwordstore','devices/do-fra1.1984.run/cjdns subkey=authorized_password_private') }}"

cjdns_udp_peers_self:
  - peerName: h.do-fra1.1984.run
    address: "{{ lookup('passwordstore','devices/do-fra1.1984.run/network_primary_ipv4') }}"
    address_type: ipv4
    port: 57338
    publicKey: "{{ cjdns_public_key }}"
    login: "private"
    password: "{{ cjdns_authorizedPasswords['private'] }}"
  - peerName: h.do-fra1.1984.run IPv6
    address: "[{{ lookup('passwordstore','devices/do-fra1.1984.run/network_primary_ipv6') }}]"
    address_type: ipv6
    port: 57338
    publicKey: "{{ cjdns_public_key }}"
    login: "private"
    password: "{{ cjdns_authorizedPasswords['private'] }}"

cjdns_udp_peers_local:
  #
  # Russia
  # Moscow
  - peerName: "h.bunjlabs.com"
    address: 94.142.141.189
    address_type: ipv4
    port: 50433
    contact: "contact@bunjlabs.com"
    publicKey: "0gdj2xzn01lzjjcrykjvwp8flnxkp1b3jny0drl5b168lmpsmfj0.k"
    login: "default-login"
    password: "c5q2j63x5nkmt2yg2vjmlnfuh1jnjjf"

  - peerName: node01.msk.ru-mesh.net
    address: 194.67.213.84
    address_type: ipv4
    port: 24519
    publicKey: 9f79752ml0p6glqdnj93352tj3hmctmf8jg8rbgp1wj8mh09lmv0.k
    login: "default-login"
    password: 37yuffz9hs4lk0wjnvyzj5yx45l444v
    contact: show.vars@gmail.com

  - peerName: h.ihc.cupivan.ru
    address: 185.87.193.205
    address_type: ipv4
    port: 18842
    publicKey: 7h898y2xdhtm9xgng7f97umx9wfjhkxfx2wkxw89mrq2y6k954d0.k
    password: public
    ipv6: fc9b:499a:dd7a:92a:7b3e:be3a:32fc:53dc

  # Piter
  - peerName: dskrylnikov
    address: 95.213.251.59
    address_type: ipv4
    port: 60246
    publicKey: v0wjlvtkxdu5tr7htymsuytwxtqlrnyjlhk59pw6s11mj4ggw7p0.k
    login: public
    password: public_passwd
    contact: skrylnikov@protonmail.com

  #
  # Ukraine
  #
  # Kiev
  - peerName: ic.hellomouse.cf
    address: 185.140.54.19
    address_type: ipv4
    port: 35907
    contact: iczero4@gmail.com
    gpg: "613CE9DA0E9A3F70EC97760E4BAC4EBB8461FC7E"
    publicKey: gtbfndu2tvfbwuydm7v0kpnqpgcburtymhz3ph9kfrjg4n8bh3j0.k
    login: public
    password: fwlmbx2f3udkd0ymknq4pwwgu2bjklx
  - peerName: ic.hellomouse.cf IPv6
    address: "[2a05:dfc7:dfc7:20::1]"
    address_type: ipv6
    port: 35907
    contact: iczero4@gmail.com
    gpg: "613CE9DA0E9A3F70EC97760E4BAC4EBB8461FC7E"
    publicKey: gtbfndu2tvfbwuydm7v0kpnqpgcburtymhz3ph9kfrjg4n8bh3j0.k
    login: public
    password: fwlmbx2f3udkd0ymknq4pwwgu2bjklx

  #
  # Sweden
  #
  - peerName: bliss.willeponken.me
    address: 130.240.202.22
    address_type: ipv4
    port: 49960
    publicKey: tpf7pdj6pby9r2smxuwmkvzfrfj6jb0brch8yhp3jsxbrf3ld0h0.k
    login: "public-peer"
    password: y4j84802yfyxpzrtbzbwtj3hd1l9mrc
    contact: "See http://bliss.willeponken.me/nodeinfo.json"

  #
  # Deutch
  #
  - peerName: weuxel.modi
    address: 195.201.148.242
    address_type: ipv4
    port: 26721
    publicKey: 1gy9myu5fhd2uhbjgju6nn54uwgz1dtr5g9r3kwsc5r9f32567s0.k
    password: public_access

  - peerName: subgroup.org
    address: 5.9.87.135
    address_type: ipv4
    port: 25761
    publicKey: hr153n9t2c4nrlzhwb9v2h5vg1sjv3bd34z3cttnbvlg97pbhwj0.k
    password: qxlr5j47jkz8hcc3jcrd50u0s379fr9

  - peerName: jazzanet
    address: 176.9.105.201
    address_type: ipv4
    port: 4464
    publicKey: yrgb0xwfr9pz8swvnv6m9by8zw7v7uxxhl07qz318cjuvfgs1fc0.k
    password: ir88xwtel72fen3ch7aug603s26nu3a
    contact: webmaster@jazzanet.com

  #
  # Netherlands
  #
  - peerName: mrowr.me
    address: 188.166.3.174
    address_type: ipv4
    port: 4841
    publicKey: s680fh7g69ww3y9cmrxt910u5hvrwrmcnln1sz6mq1jk5mquq8k0.k
    password: public-20150903-6pb6aEKDDKVr9zsBJIyDUYfrXYzQv1

  - peerName: unloved.vultar.ams
    address: 45.76.38.114
    address_type: ipv4
    port: 19621
    publicKey: vxh6lcjqgpgswbwmwu6wxd9kntflhwbpxfsw83ks9yf34jcqb7b0.k
    password: 773vp0snvpjfnn5wb6pc4x5xl6j229v

  #
  # France
  #
  - peerName: whoami.paris.fr
    address: 163.172.148.88
    address_type: ipv4
    port: 43418
    publicKey: nkzuf1j0tzthxv4l4vyrbtjdwjn8b4t8fhst40bx6q803260vuc0.k
    password: Xo0zSL4g7vGMW6_IMJb6AixTKxu4a7vo

  - peerName: whoami.paris.fr IPv6
    address: "[2001:bc8:4400:2900::2:929]"
    address_type: ipv6
    port: 43418
    publicKey: nkzuf1j0tzthxv4l4vyrbtjdwjn8b4t8fhst40bx6q803260vuc0.k
    password: Xo0zSL4g7vGMW6_IMJb6AixTKxu4a7vo

  - peerName: h.totem.tfnux.org
    address: 163.172.26.210
    address_type: ipv4
    port: 27410
    publicKey: 8bqv77rkzn888mcr8wu3k9b22hpczhn7c0zzyrqpj4bbx8rbf810.k
    password: ZGZWKOX5H535MG7MRYRKFMF4IY5GFCO5

  - peerName: h.totem.tfnux.org IPv6
    address: "[2001:bc8:2495:100::1]"
    address_type: ipv6
    port: 27410
    publicKey: 8bqv77rkzn888mcr8wu3k9b22hpczhn7c0zzyrqpj4bbx8rbf810.k
    password: ZGZWKOX5H535MG7MRYRKFMF4IY5GFCO5

  - peerName: h.akru.me
    address: 164.132.111.49
    address_type: ipv4
    port: 53741
    publicKey: 35mdjzlxmsnuhc30ny4rhjyu5r1wdvhb09dctd1q5dcbq6r40qs0.k
    password: cr36pn2tp8u91s672pw2uu61u54ryu8

  - peerName: h.akru.me IPv6
    address: "[2001:41d0:401:3100::34e6]"
    address_type: ipv6
    port: 53741
    publicKey: 35mdjzlxmsnuhc30ny4rhjyu5r1wdvhb09dctd1q5dcbq6r40qs0.k
    password: cr36pn2tp8u91s672pw2uu61u54ryu8

  - peerName: h.rwfr.k
    address: 164.132.126.140
    address_type: ipv4
    port: 53340
    publicKey: byxcwmgbhkcgt3vv2820vujbc65szwkn9sj7vk1x3tjdw4q0sc30.k
    password: w6db8n5gb4wtjy0ud32vhql7469g1sb

  - peerName: Magik6k-sbg1
    address: 51.254.25.16
    address_type: ipv4
    port: 1132
    publicKey: kw0vfw3tmb6u6p21z5jmmymdlumwknlg3x8muk5mcw66tdpqlw30.k
    password: thah9aePha1Vusha6ovhpublic

  #
  # Latvia
  #
  - peerName: borg-vilnius
    address: 185.25.48.153
    address_type: ipv4
    port: 13109
    publicKey: pkq30hrl9zyzwn03u6lchh20crfgq46m1dfb5zwfhpx3c6v2l420.k
    password: public

  #
  # Norwegia
  #
  - peerName: hyperboria.hackeriet.no
    address: 185.35.202.206
    address_type: ipv4
    port: 21024
    publicKey: ny7v0951b703j4t2n4pyz474nny46wvbtq46x7hc8r2jql40dmr0.k
    password: tj0vkzk9rgub9888h3tf9gtm712tkuc

  - peerName: hyperboria.hackeriet.no IPv6
    address: "[2a02:ed06::206]"
    address_type: ipv6
    port: 21024
    publicKey: ny7v0951b703j4t2n4pyz474nny46wvbtq46x7hc8r2jql40dmr0.k
    password: tj0vkzk9rgub9888h3tf9gtm712tkuc


  #
  # Czech
  #
  - peerName: foxcool.hukot
    address: 46.36.36.207
    address_type: ipv4
    port: 42947
    publicKey: nf2vn4n1jwlk50v0yq79vu5vb3srl8rg4ux3ud7p93k2qy54bbt0.k
    password: ditributedmeshnetBa568cKlGl6kPqwmnRy85lm3V8iV


cjdns_udp_peers: "{{
  cjdns_udp_peers_common|difference(cjdns_udp_peers_self) +  cjdns_udp_peers_local
}}"
