---
wireguard_private_key: "{{ lookup('passwordstore','devices/do-fra1.1984.run/wireguard subkey=private') }}"
wireguard_public_key: "{{ lookup('passwordstore','devices/do-fra1.1984.run/wireguard subkey=public') }}"

wireguard_servers_dns_listen:
  - "10.66.7.1:53:53/udp"
wireguard_servers:
  - name: wg0
    description: Family server
    private_key: "{{ wireguard_private_key }}"
    public_key: "{{ wireguard_public_key }}"
    port: 51820
    addresses:
      - 10.66.7.1/27
    routes:
      - gateway: '10.66.7.5'
        destination: '10.66.6.0/24'
    peers:
      - name: alien
        public_key: "{{ hostvars['alien.1984.run']['wireguard_public_key'] }}"
        allowed_ips:
          - 10.66.7.2/32
      - name: mi5sergey
        public_key: "4BHFbGsH26ItEbnb7tMSK6tDqjzBEH1uUe99HbfvjBA="
        allowed_ips:
          - 10.66.7.3/32
      - name: knopa
        public_key: "CqxACHryJN5pnTNoHZb0C9zbMoHy9IOUgbfmqaOBJQQ="
        allowed_ips:
          - 10.66.7.4/32
      - name: mir3g
        public_key: "{{ lookup('passwordstore','devices/mir3g.1984.run/wireguard subkey=public') }}"
        allowed_ips:
          - 10.66.6.0/23

# TODO:
