---
- name: Add flatpak remotes
  flatpak_remote:
    name: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    flatpakrepo_url: "{{ item.flatpakrepo_url }}"
    method: "{{ item.method|default('system') }}"
  with_items: "{{ flatpak_remotes }}"
  failed_when: None
  tags: flatpak

- name: Manage flatpaks
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote|default('flathub') }}"
    state: "{{ item.state|default('present') }}"
    method: "{{ item.method|default('system') }}"
  with_items: "{{ flatpaks }}"
  tags: flatpak

- name: Install Telegram desktop file (fix unstability)
  copy:
    src: org.telegram.desktop.desktop
    dest: "{{ lookup('env','XDG_DATA_HOME') }}/applications/org.telegram.desktop.desktop"
  tags: flatpak
