#!/usr/bin/env bash

set -e

CHANGED=$(git diff --cached --name-only --diff-filter=ACM)

echo "$CHANGED" | grep -q '\.nix$' || : | xargs -r nixpkgs-fmt --check

SHS=$(echo "$CHANGED" | grep -qe '\.sh$\|^\.githooks' || :)
echo "$SHS" | xargs -r shfmt -i 2 -d
echo "$SHS" | xargs -r shellcheck
