#!/usr/bin/env bash

set -e

CHANGED=$(git diff --cached --name-only --diff-filter=ACM)

NIXS=$(echo "$CHANGED" | (grep -e '\.nix$' || :) | grep -ve 'nix/sources\.nix$')

echo "$NIXS" | xargs -r nixpkgs-fmt --check

SHS=$(echo "$CHANGED" | grep -e '\.sh$\|^\.githooks' || :)
echo "$SHS" | xargs -r shfmt -i 2 -d
echo "$SHS" | xargs -r shellcheck
