keys:
  - &sk DF82B446BE5D7508473E47BF58A58B6FD38C6B66
  - &alien 721b065c27bdbcc8682dcea1bf252f6be38fec14

creation_rules:
  - path_regex: users/sk/secrets/[^/]+$
    key_groups:
      - pgp:
          - *sk
          - *alien
  - path_regex: hosts/alien/secrets/[^/]+$
    key_groups:
      - pgp:
          - *sk
          - *alien
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *sk
          - *alien
  - path_regex: .*
