---
- name: Create directories for CACHEDIR.TAG files
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ cachedirs }}"
  tags: cachedir

- name: Create CACHEDIR.TAG files
  copy:
    src: CACHEDIR.TAG
    dest: "{{ item }}/CACHEDIR.TAG"
  with_items: "{{ cachedirs }}"
  tags: cachedir
