---
- name: tersmitten.sysctl
  version: v1.0.18
- name: willshersystems.sshd
  version: v0.6.1
- name: GROG.group
  version: v1.1.2
- name: GROG.management-user
  version: v1.2.7
- name: shhirose.locale
  version: v0.1.0

