---
- name: Create directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - path: /etc/nixos/secrets
      owner: root
      group: root
      mode: "0755"
  notify:
    - nixos-rebuild

- name: Push secrets
  copy:
    content: "{{ item.content }}"
    dest: "/etc/nixos/secrets/{{ item.name }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.owner|default('root') }}"
    mode: "{{ item.owner|default('0640') }}"
  no_log: yes
  with_items:
    - "{{ nixos_secrets }}"
  notify:
    - nixos-rebuild

