---
galaxy_info:
  author: G. Roggemans
  description: A role for managing groups.
  company: GROG
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: GenericUNIX
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  galaxy_tags:
  - group
  - system

allow_duplicates: yes

dependencies: []
