---
- name: Create cjdroute.conf
  tags: cjdns
  template:
    src: cjdroute.conf.j2
    dest: /etc/cjdroute.conf
    owner: root
    mode: 0600
  notify:
    - restart cjdns

- name: Enable cjdns service
  tags: cjdns
  systemd:
    name: cjdns.service
    state: started
    enabled: yes

- name: Enable cjdns-resume service
  tags: cjdns
  systemd:
    name: cjdns-resume.service
    enabled: yes

- name: Enable cjdns ports on public firewalld zone
  tags: firewalld, cjdns
  firewalld:
    zone: public
    port: "{{ item.bind.split(':')[-1] }}/udp"
    state: enabled
    immediate: yes
    permanent: yes
  with_items: "{{ cjdns_udp_interfaces }}"

- name: Add cjdns interface to public firewalld zone
  tags: cjdns, firewalld
  firewalld:
    interface: "{{ cjdns_tun_device }}"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
