---
# Gather facts
- name: Gather facts about ostree deployment
  command: rpm-ostree status --json
  register: rpmostree_status_raw
  changed_when: false
  check_mode: no
  tags: rpm-ostree-install

- name: Set fact about ostree deployment
  set_fact: installed="{{ (rpmostree_status_raw.stdout | from_json | json_query(query))[0][0] }}"
  vars:
    query: "deployments[?booted][\"requested-packages\"]"
  tags: rpm-ostree-install

- name: Install packages
  command: "rpm-ostree install --unchanged-exit-77 --idempotent {{ rpm_ostree_install|join(' ') }}"
  register: result
  changed_when: result.rc != 77
  failed_when: result.rc != 0 and result.rc != 77
  when: rpm_ostree_install|length > 0
  tags: rpm-ostree-install

- name: Uninstall packages
  command: "rpm-ostree uninstall --idempotent {{ installed|difference(rpm_ostree_install)|join(' ') }}"
  register: result
  changed_when: result.rc != 77
  failed_when: result.rc != 0 and result.rc != 77
  when: installed|difference(rpm_ostree_install)|length > 0
  tags: rpm-ostree-install
