---
- name: Get file status
  stat:
    path: "{{ binary.dest }}"
  register: filestat
  tags: binary-installer

- when: not filestat.stat.exists or filestat.stat.checksum != binary.checksum
  tags: binary-installer
  block:
    - name: Create temporary directory
      tempfile: state=directory
      register: tmpdir
      tags: binary-installer

    - name: Download and extract binary
      unarchive:
        src: "{{ binary.url }}"
        remote_src: yes
        dest: "{{ tmpdir.path }}"
      tags: binary-installer

    - name: Copy binary to destination
      copy:
        src: "{{ tmpdir.path }}/{{ binary.archive_path }}"
        remote_src: yes
        dest: "{{ binary.dest }}"
        owner: root
        mode: 0755
      tags: binary-installer

    - name: Remove temporary directory
      file: state=absent path="{{ tmpdir.path }}"
      tags: binary-installer



