---
# gnupg
GPG_DEFAULT_KEY: null

# tmux
tmux_data_dir: "{{ lookup('env','XDG_DATA_HOME') }}/tmux"

# vim
vim_config_dir: "{{ lookup('env','XDG_CONFIG_HOME') }}/vim"
vim_data_dir: "{{ lookup('env','XDG_DATA_HOME') }}/vim"
vim_cache_dir: "{{ lookup('env','XDG_CACHE_HOME') }}/vim"

# zsh
ZDOTDIR: "{{ lookup('env','XDG_CONFIG_HOME') }}/zsh"
ZDATADIR: "{{ lookup('env','XDG_DATA_HOME') }}/zsh"
ZCACHEDIR: "{{ lookup('env','XDG_CACHE_HOME') }}/zsh"
