---
- name: Create dunst config directory
  file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/dunst"
    state: directory
  tags: dunst

- name: Deploy dunst config
  template:
    src: dunst.j2
    dest: "{{ lookup('env','XDG_CONFIG_HOME') }}/dunst/dunstrc"
  tags: dunst
  notify: restart dunst

- name: Create sway config directory
  file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/sway"
    state: directory
  tags: sway

- name: Deploy sway config
  template:
    src: sway.j2
    dest: "{{ lookup('env','XDG_CONFIG_HOME') }}/sway/config"
  tags: sway
