---
ansible_user: root
ansible_host: z.alien.1984.run
ansible_python_interpreter: /usr/bin/env python3
nixos_channels_add:
  nixos: https://nixos.org/channels/nixos-19.03
nixos_channels_remove: []
nixos_secrets:
  - name: root_password
    content: "{{ lookup('passwordstore','devices/alien.1984.run/root')|password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
  - name: sk_password
    content: "{{ lookup('passwordstore','devices/alien.1984.run/sk')|password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
  - name: azire_wg_priv
    content: "{{ lookup('passwordstore','devices/alien.1984.run/azire_wg_priv') }}"
