---
management_user_list_host:
  - name: sk
    uid: 1000
    password: "{{ sk_password|password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
    update_password: always
    group: sk
    groups:
      - sk
      - adm
      - wheel
      - mail
      - games
      - video
      - users
      - power
      - libvirt
    shell: /bin/zsh
    authorized_keys:
      - key: "{{ lookup('passwordstore','keys/ssh_knopki subkey=public') }}"
        exclusive: yes
        manage_dir: yes
    sudo:
      hosts: ALL
      as: ALL
      commands: ALL
      nopasswd: yes

polkit_default_operators_nopasswd_host:
  - sk
