---
wireguard_private_key: "{{ lookup('passwordstore','devices/alien.1984.run/wireguard subkey=private') }}"
wireguard_public_key: "{{ lookup('passwordstore','devices/alien.1984.run/wireguard subkey=public') }}"
wireguard_clients:
  - name: wg0
    description: do-fra1
    private_key: "{{ wireguard_private_key }}"
    public_key: "{{ wireguard_public_key }}"
    port: 19840
    addresses:
      - 10.66.7.2/27
    peers:
      - name: do-fra1
        public_key: "{{ hostvars['do-fra1.1984.run']['wireguard_public_key'] }}"
        allowed_ips:
          - 0.0.0.0/0
          - ::/0
        endpoint: do-fra1.1984.run:19840
