---
- name: Create git config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ lookup('env','XDG_CONFIG_HOME') }}/git"
    - "{{ lookup('env','XDG_CONFIG_HOME') }}/git/info"
  tags: shell, git

- name: Deploy git configuration
  copy:
    src: "git/{{ item }}"
    dest: "{{ lookup('env','XDG_CONFIG_HOME') }}/git/{{ item }}"
  with_items:
    - info/ignore
  tags: shell, git

- name: Deploy git configuration
  template:
    src: "git/{{ item }}.j2"
    dest: "{{ lookup('env','XDG_CONFIG_HOME') }}/git/{{ item }}"
  with_items:
    - config
  tags: shell, git
