---
- name: Set Gtk3 settings
  ini_file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/gtk-3.0/settings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ gtk3_settings_add }}"
  tags: dotfiles, shell, gtk

- name: Unset Gtk3 settings
  ini_file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/gtk-3.0/settings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: absent
  with_items: "{{ gtk3_settings_remove }}"
  tags: dotfiles, shell, gtk

- name: Set Gtk4 settings
  ini_file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/gtk-4.0/settings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ gtk4_settings_add }}"
  tags: dotfiles, shell, gtk

- name: Unset Gtk4 settings
  ini_file:
    path: "{{ lookup('env','XDG_CONFIG_HOME') }}/gtk-4.0/settings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: absent
  with_items: "{{ gtk4_settings_remove }}"
  tags: dotfiles, shell, gtk

- name: Set Gtk bookmarks
  template:
    src: gtk/bookmarks.j2
    dest: "{{ lookup('env','XDG_CONFIG_HOME') }}/gtk-3.0/bookmarks"
  tags: dotfiles, shell, gtk
