---
- name: Create tmux data directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tmux_data_dir }}"
    - "{{ tmux_data_dir }}/plugins"
    - "{{ lookup('env','HOME') }}/.tmux"
    - "{{ lookup('env','HOME') }}/.tmux/powerline"
    - "{{ lookup('env','HOME') }}/.tmux/powerline/segments"
    - "{{ lookup('env','HOME') }}/.tmux/powerline/themes"
  tags: shell, tmux

- name: Download tmux-sentsible plugin
  git:
    repo: https://github.com/tmux-plugins/tmux-sensible.git
    dest: "{{ tmux_data_dir }}/plugins/tmux-sensible"
    version: v3.0.0
    depth: 1
  tags: shell, tmux

- name: Download tmux-pain-control plugin
  git:
    repo: https://github.com/tmux-plugins/tmux-pain-control.git
    dest: "{{ tmux_data_dir }}/plugins/tmux-pain-control"
    version: v1.0.0
    depth: 1
  tags: shell, tmux

- name: Download tmux-resurrect plugin
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect.git
    dest: "{{ tmux_data_dir }}/plugins/tmux-resurrect"
    version: v1.0.0
    depth: 1
  tags: shell, tmux

- name: Download tmux-colors-solarized plugin
  git:
    repo: https://github.com/seebi/tmux-colors-solarized.git
    dest: "{{ tmux_data_dir }}/plugins/tmux-colors-solarized"
    version: b74be1f5076240d278e78b6fd132d531d5c41cda
  tags: shell, tmux

- name: Download tmux-powerline plugin
  git:
    repo: https://github.com/erikw/tmux-powerline.git
    dest: "{{ tmux_data_dir }}/plugins/tmux-powerline"
    version: V1.1
    depth: 1
  tags: shell, tmux

- name: Deploy tmux configs
  copy:
    src: "tmux/{{ item }}"
    dest: "{{ lookup('env','HOME') }}/{{ item }}"
  with_items:
    - .tmux-powerlinerc
    - .tmux/powerline/segments/context.sh
    - .tmux/powerline/segments/cpu.sh
    - .tmux/powerline/segments/mem.sh
    - .tmux/powerline/segments/tmux_session_info.sh
    - .tmux/powerline/segments/uptime.sh
    - .tmux/powerline/themes/mytheme.sh
  tags: shell, tmux

- name: Deploy tmux main config
  template:
    src: "tmux/tmux.j2"
    dest: "{{ lookup('env','HOME') }}/.tmux.conf"
  tags: shell, tmux
