---
- name: Update atomic-wireguard sysconfig
  tags: wireguard
  template:
    src: wireguard-sysconfig.j2
    dest: /etc/sysconfig/atomic-wireguard
    owner: root
    mode: 0644

- name: Enable atomic-wireguard.service
  systemd:
    name: atomic-wireguard.service
    enabled: yes
    state: started
  tags: wireguard

- name: Copy netdev files
  tags: wireguard
  template:
    src: netdev.j2
    dest: "/etc/systemd/network/{{ item.name }}.netdev"
    owner: root
    group: systemd-network
    mode: 0640
  with_items: "{{ wireguard_servers }}"
  notify:
    - systemctl restart systemd-networkd

- name: Copy network files
  tags: wireguard
  template:
    src: network.j2
    dest: "/etc/systemd/network/{{ item.name }}.network"
    owner: root
    group: systemd-network
    mode: 0640
  with_items: "{{ wireguard_servers }}"
  notify:
    - systemctl restart systemd-networkd

- name: Enable systemd-networkd.service
  systemd:
    name: systemd-networkd.service
    enabled: yes
    state: started
  tags: wireguard

- name: Enable wireguard ports on public firewalld zone
  tags: firewalld
  firewalld:
    zone: public
    port: "{{ item.port }}/udp"
    state: enabled
    immediate: yes
    permanent: yes
  with_items: "{{ wireguard_servers }}"

- name: Enable internal firewalld zone
  tags: firewalld, wireguad
  firewalld:
    zone: internal
    state: present
    permanent: yes

- name: Add wireguard interface to internal firewalld zone
  tags: wireguard, firewalld
  firewalld:
    interface: "{{ item.name }}"
    zone: internal
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ wireguard_servers }}"

