---
- name: Enable default firewalld zone
  tags: firewalld
  firewalld:
    zone: "{{ firewalld_default_zone }}"
    state: present
    permanent: yes

- name: Enable default services in default firewalld zone
  tags: firewalld
  firewalld:
    zone: "{{ firewalld_default_zone }}"
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ firewalld_default_services }}"

- name: Add interface to default zone
  tags: firewalld
  when: firewalld_add_interface_to_zone is defined
  firewalld:
    interface: "{{ firewalld_add_interface_to_zone }}"
    zone: "{{ firewalld_default_zone }}"
    state: enabled
    permanent: yes
    immediate: yes
