---
all:
  children:
    fedora-atomic:
      hosts:
        do-fra1.1984.run:
        knopa.1984.run:
    windows:
    docker:
    servers:
      hosts:
        do-fra1.1984.run:
    workstations:
      hosts:
        alien.1984.run:
        knopa.1984.run:
    mtproxy:
      hosts:
        do-fra1.1984.run:
    do-agent:
      hosts:
        do-fra1.1984.run:
    openwrt:
      hosts:
        mir3g.1984.run:
