---
all:
  children:
    fedoraatomic:
      hosts:
        do-fra1.1984.run:
        knopa.1984.run:
    servers:
      hosts:
        do-fra1.1984.run:
    workstations:
      hosts:
        alien.1984.run:
        knopa.1984.run:
        panzer.1984.run:
    nixos:
      hosts:
        alien.1984.run:
        oberon.1984.run:
        panzer.1984.run:
