---
- hosts: do-fra1.1984.run
  any_errors_fatal: true
  become: true
  roles:
    - role: deploy-local-facts
      tags: facts

    # Packages
    - role: yum-repos
      tags: yum-repos
    - role: rpm-ostree-upgrade
      tags: rpm-ostree-upgrade
    - role: rpm-ostree-install
      tags: rpm-ostree-install
    - role: binary-installer
      tags: binary-installer

    # Essential settings and services
    - role: hostname
      tags: hostname
    - role: timezone
      tags: timezone
    - role: shhirose.locale
      tags: locale
      shhirose_locale_locale: "{{ system_locale }}"
    - role: chrony
      tags: chrony
    - role: tersmitten.sysctl
      tags: sysctl
      sysctl_settings: '{{
        sysctl_default_parameters|d([]) +
        sysctl_group_parameters|d([]) +
        sysctl_host_parameters|d([])
      }}'
    - role: modprobe-permanent
      tags: modprobe_permanent
    - role: tuned
      tags: tuned
    - role: firewalld-common
      tags: firewalld
    - role: cjdns
      tags: cjdns
    - role: nm
      tags: networkmanager

    # User management
    - role: GROG.group
      tags: groups
    - role: GROG.management-user
      tags: users
    - role: polkit-operators
      tags: polkit
    - role: willshersystems.sshd
      tags: sshd
      sshd: '{{
        sshd_default_parameters|d({}) |
        combine(sshd_group_parameters|d({})) |
        combine(sshd_host_parameters|d({}))
      }}'
      sshd_packages: []

- hosts: do-fra1.1984.run
  any_errors_fatal: true
  become: true
  tasks:
    - name: Add interface eth0 to public firewalld zone
      tags: firewalld
      firewalld:
        interface: eth0
        zone: public
        state: enabled
        permanent: yes
        immediate: yes

    - name: Add interface cni0 to trusted firewalld zone
      tags: firewalld
      firewalld:
        interface: cni0
        zone: trusted
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable masquerade on public firewalld zone
      tags: firewalld
      firewalld:
        zone: public
        masquerade: yes
        state: enabled
        immediate: yes
        permanent: True

- hosts: do-fra1.1984.run
  any_errors_fatal: true
  become: true
  roles:
    - name: do-agent
      tags: do-agent
    - role: mtproxy
      tags: mtproxy
    - role: openvpn-server
      tags: openvpn-server
    - role: polipo
      tags: polipo
