---
- hosts: servers
  any_errors_fatal: true
  become: true
  become_user: "{{ main_user }}"
  roles:
  - role: dotfiles-environmentd
    tags: environmentd
  - role: dotfiles-shell
    tags: shell

