---
- hosts: knopa.1984.run
  any_errors_fatal: true
  become: true
  roles:
    - role: deploy-local-facts
      tags: facts

    # Packages
    - role: yum-repos
      tags: yum-repos
    - role: rpm-ostree-upgrade
      tags: rpm-ostree-upgrade
    - role: rpm-ostree-install
      tags: rpm-ostree-install
    - role: binary-installer
      tags: binary-installer
    - role: flatpak
      tags: flatpak
    - role: pip
      tags: pip

    # Essential settings and services
    - role: hostname
      tags: hostname
    - role: timezone
      tags: timezone
    - role: shhirose.locale
      tags: locale
      shhirose_locale_locale: "{{ system_locale }}"
    - role: chrony
      tags: chrony
    - role: tersmitten.sysctl
      tags: sysctl
      sysctl_settings: '{{
        sysctl_default_parameters|d([]) +
        sysctl_group_parameters|d([]) +
        sysctl_host_parameters|d([])
      }}'
    - role: modprobe-permanent
      tags: modprobe_permanent
    - role: vconsole
      tags: vconsole
    - role: tuned
      tags: tuned
    - role: thermald
      tags: thermald
    - role: firewalld-common
      tags: firewalld
      firewalld_add_interface_to_zone: enp0s31f6
    - role: cjdns
      tags: cjdns
    - role: gdm
      tags: gdm
    - role: nm
      tags: networkmanager
    - role: lm-sensors
      tags: lm-sensors
    - role: fonts
      tags: fonts

    # User management
    - role: GROG.group
      tags: groups
    - role: GROG.management-user
      tags: users
    - role: polkit-operators
      tags: polkit
    - role: willshersystems.sshd
      tags: sshd
      sshd: '{{
        sshd_default_parameters|d({}) |
        combine(sshd_group_parameters|d({})) |
        combine(sshd_host_parameters|d({}))
      }}'
      sshd_packages: []

    # Specific
    - role: openvpn-client
      tags: openvpn
      client_name: mullvad
      ca: "{{ mullvad_ca }}"
      crl: "{{ mullvad_crl }}"
      userpass: "{{ mullvad_userpass }}"
      config: "{{ mullvad_config }}"
    - role: zerotier
      tags: zerotier
      zerotier_network_id: "{{ lookup('passwordstore', 'keys/zerotier/1984/network_id') }}"
      zerotier_access_token: "{{ lookup('passwordstore', 'keys/zerotier/knopki subkey=access_token') }}"
      zerotier_firewalld_zone: public
      zerotier_member_ip_assignments:
        - 172.25.0.101
        - fccc:be38:6292:c919:fb79::1

