{ ... }: {
  imports = [
    ./alacritty.nix
    ./cachedir.nix
    ./chromium.nix
    ./curl.nix
    ./desktop-pack.nix
    ./devops.nix
    ./editorconfig.nix
    ./env.nix
    ./firefox.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./gnome.nix
    ./htop.nix
    ./jsdev.nix
    ./kitty.nix
    ./neovim.nix
    ./nixdev.nix
    ./qt.nix
    ./readline.nix
    ./ssh.nix
    ./swaywm.nix
    ./termite.nix
    ./tmux.nix
    ./vscode.nix
    ./wget.nix
    ./xdg.nix
  ];
}
