---
- name: Reload the SSH service
  service:
    name: "{{ sshd_service }}"
    state: reloaded
  when: "sshd_allow_reload and ansible_virtualization_type|default(None) != 'docker'"
  listen: reload_sshd
