---
cjdns_private_key: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=private') }}"
cjdns_public_key: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=public') }}"
cjdns_ipv6: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=ipv6') }}"
cjdns_admin_password: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=admin_password') }}"
cjdns_authorizedPasswords:
  default-login: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=authorized_password_default_login') }}"
  private: "{{ lookup('passwordstore','devices/knopa.1984.run/cjdns subkey=authorized_password_private') }}"

cjdns_udp_peers_self: []

cjdns_udp_peers_local:
  - peerName: h.mir3g.1984.run
    address: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/network_primary_ipv4') }}"
    address_type: ipv4
    port: 57338
    publicKey: "{{ hostvars['mir3g.1984.run']['cjdns_public_key'] }}"
    login: "private"
    password: "{{ hostvars['mir3g.1984.run']['cjdns_authorizedPasswords']['private'] }}"
  - peerName: h.alien.1984.run
    address: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/network_primary_ipv4') }}"
    address_type: ipv4
    port: 57339
    publicKey: "{{ hostvars['alien.1984.run']['cjdns_public_key'] }}"
    login: "private"
    password: "{{ hostvars['alien.1984.run']['cjdns_authorizedPasswords']['private'] }}"

cjdns_udp_peers: "{{
  cjdns_udp_peers_common|difference(cjdns_udp_peers_self) +  cjdns_udp_peers_local
}}"
