---
- hosts: fedora-atomic
  any_errors_fatal: true
  become: true
  roles:
    - role: shhirose.locale
      tags: locale
      shhirose_locale_locale: "{{ system_locale }}"

    - role: chrony
      tags: chrony
      when: ansible_local.installed_packages is defined
        and 'chrony' in ansible_local.installed_packages

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      tags: hostname

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"
      tags: timezone
      when: timezone is defined

    - include_tasks: tasks/yum-repos.yml
      tags: yum-repos
    - include_tasks: tasks/rpm-ostree.yml
      tags:
        - rpm-ostree-upgrade
        - rpm-ostree-install

    - name: Enable public firewalld zone
      tags: firewalld
      firewalld:
        zone: public
        state: present
        permanent: yes

    - name: Enable ssh service in public firewalld zone
      tags: firewalld
      firewalld:
        zone: public
        service: ssh
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable mdns service in public firewalld zone
      tags: firewalld
      firewalld:
        zone: public
        service: mdns
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable dhcpv6-client service in public firewalld zone
      tags: firewalld
      firewalld:
        zone: public
        service: dhcpv6-client
        state: enabled
        permanent: yes
        immediate: yes

