---
- name: Deploy polipo
  docker_container:
    name: polipo
    image: docker.io/clue/polipo:latest
    restart_policy: always
    memory: 64m
    memory_reservation: 16m
    state: started
    ports:
      - "{{polipo_port}}:8123"
    entrypoint: "polipo proxyAddress='::0' authCredentials={{polipo_username}}:{{polipo_password}}"

- name: Enable 3128 port for polipo on public firewalld zone
  tags: firewalld, polipo
  firewalld:
    zone: public
    port: 3128/tcp
    state: enabled
    immediate: yes
    permanent: yes
