---
atomic_host_remote_name: "fedora-workstation"
atomic_host_remote_url: "https://dl.fedoraproject.org/atomic/repo/"
atomic_host_remote_gpg_verify: "true"
atomic_host_desired_ref: "fedora/28/x86_64/workstation"
atomic_host_desired_version: "28.20180630.0"
atomic_host_autoupgrade: check
rpm_ostree_install_group:
  - android-tools
  - ansible
  - bcache-tools
  - borgbackup
  - cabextract
  - chromium
  - chromium-pepper-flash
  - clementine
  - code
  - createrepo
  - dolphin
  - feh
  - flash-plugin
  - golang
  - google-cloud-sdk
  - hdparm
  - htop
  - iftop
  - iotop
  - kde-connect
  - kde-print-manager
  - kde-settings
  - kdeplasma-addons
  - kgpg
  - konsole5
  - kscreen
  - ktimetracker
  - kwalletmanager5
  - langpacks-ru
  - libvirt
  - mc
  - mpv
  - nmap
  - node-gyp
  - nodejs
  - npm
  - p7zip
  - pass
  - plasma-desktop
  - plasma-nm-l2tp
  - plasma-workspace
  - powertop
  - sddm
  - sddm-breeze
  - sddm-kcm
  - spectacle
  - speedcrunch
  - switchdesk
  - syncthing
  - thermald
  - tmux
  - torbrowser-launcher
  - tuned
  - vim-enhanced
  - virt-manager
  - wireshark
  - youtube-dl
  - zsh
