---
yum_repos_group:
  - name: google-cloud-sdk
    baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64"
    enabled: 1
    gpgcheck: 0
    repo_gpgcheck: 0
  - name: kubernetes
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  - name: microsoft
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    enabled: 1
    gpgcheck: 1
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
  - name: code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

