# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  base16-default-schemes = {
    pname = "base16-default-schemes";
    version = "daf674291964321cd8c92644f9bbdbf3e7c0e8b3";
    src = fetchgit {
      url = "https://github.com/chriskempson/base16-default-schemes";
      rev = "daf674291964321cd8c92644f9bbdbf3e7c0e8b3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1hdhvl7xr068z5pcib2jja6kjl7l4v2q8l4cihjgk1l7yqf440m7";
    };
  };
  base16-dracula-scheme = {
    pname = "base16-dracula-scheme";
    version = "9494b73c343dde092edb05db51f1fd238395f10a";
    src = fetchgit {
      url = "https://github.com/dracula/base16-dracula-scheme";
      rev = "9494b73c343dde092edb05db51f1fd238395f10a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1wki4whq4m83i7x5c0j6plhjp7n1z9k33q0xgbnbbfdj9xivyxw8";
    };
  };
  base16-shell = {
    pname = "base16-shell";
    version = "ce8e1e540367ea83cc3e01eec7b2a11783b3f9e1";
    src = fetchgit {
      url = "https://github.com/chriskempson/base16-shell";
      rev = "ce8e1e540367ea83cc3e01eec7b2a11783b3f9e1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1yj36k64zz65lxh28bb5rb5skwlinixxz6qwkwaf845ajvm45j1q";
    };
  };
  base16-textmate = {
    pname = "base16-textmate";
    version = "1d9e52afb74e03f5a2fdc53d9327428fe00c70c7";
    src = fetchgit {
      url = "https://github.com/chriskempson/base16-textmate";
      rev = "1d9e52afb74e03f5a2fdc53d9327428fe00c70c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1h10ynqdrnh9xh9pxjzrd2yk85zavmmqs9mx6hb2v0dq4m81hkmr";
    };
  };
  base16-tmux = {
    pname = "base16-tmux";
    version = "810ba8f86f028b467353e22837f8c89eb46fc287";
    src = fetchgit {
      url = "https://github.com/mattdavis90/base16-tmux";
      rev = "810ba8f86f028b467353e22837f8c89eb46fc287";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1r5gr61c72ab6i3bpx14r4233zl0rkwg60r17kkhvml0gdpx4w08";
    };
  };
  base16-vim = {
    pname = "base16-vim";
    version = "6191622d5806d4448fa2285047936bdcee57a098";
    src = fetchgit {
      url = "https://github.com/chriskempson/base16-vim";
      rev = "6191622d5806d4448fa2285047936bdcee57a098";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1qz21jizcy533mqk9wff1wqchhixkcfkysqcqs0x35wwpbri6nz8";
    };
  };
  base16-waybar = {
    pname = "base16-waybar";
    version = "d2f943b1abb9c9f295e4c6760b7bdfc2125171d2";
    src = fetchgit {
      url = "https://github.com/mnussbaum/base16-waybar";
      rev = "d2f943b1abb9c9f295e4c6760b7bdfc2125171d2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1kc4w98rbdb3lyqrf8lzc1xsgn1zxqlzwxry6fiz89ygn84gh5ks";
    };
  };
  dracula-alacritty = {
    pname = "dracula-alacritty";
    version = "dd73876ccba4f7dbd8f4422fec414e96253938de";
    src = fetchgit {
      url = "https://github.com/dracula/alacritty";
      rev = "dd73876ccba4f7dbd8f4422fec414e96253938de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1438yy362wryifj5jrzmzxbg518xwwy352972g5y4rms9pb9y43l";
    };
  };
  dracula-fish = {
    pname = "dracula-fish";
    version = "62b109f12faab5604f341e8b83460881f94b1550";
    src = fetchgit {
      url = "https://github.com/dracula/fish";
      rev = "62b109f12faab5604f341e8b83460881f94b1550";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0ljk8fbyjb7519k2g1yhsv85b75ckf9yqvmspy0qxn5bdfmllffi";
    };
  };
  dracula-wofi = {
    pname = "dracula-wofi";
    version = "04f905b10796f9491f30be024b0b5ff28c675648";
    src = fetchgit {
      url = "https://github.com/dracula/wofi";
      rev = "04f905b10796f9491f30be024b0b5ff28c675648";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1ragsld4pn787vi7pwi5pi8p685vnrkn5l68xir9j327511glqms";
    };
  };
  dracula-zathura = {
    pname = "dracula-zathura";
    version = "b597b1537aa125e8829bef2cc57a0b0c6a6b35a1";
    src = fetchgit {
      url = "https://github.com/dracula/zathura";
      rev = "b597b1537aa125e8829bef2cc57a0b0c6a6b35a1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0x75invwibilw1gqvrnl9fffghb6fy27fdqp4h2x8hrlzk0g3aw3";
    };
  };
  fish-kubectl-completions = {
    pname = "fish-kubectl-completions";
    version = "ced676392575d618d8b80b3895cdc3159be3f628";
    src = fetchgit {
      url = "https://github.com/evanlucas/fish-kubectl-completions";
      rev = "ced676392575d618d8b80b3895cdc3159be3f628";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "09qcj82qfs4y4nfwvy90y10xmx6vc9yp33nmyk1mpvx0dx6ri21r";
    };
  };
  ls-colors = {
    pname = "ls-colors";
    version = "52efc3b3df66fcc1ea19c8edeba769d5e42c7b97";
    src = fetchgit {
      url = "https://github.com/trapd00r/LS_COLORS";
      rev = "52efc3b3df66fcc1ea19c8edeba769d5e42c7b97";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1gxdmsc4ba1v3f0q7kx8fxnqpq184n90i2sqkkqx3d7p2m8i4l9i";
    };
  };
}
