---
flatpak_remotes_default:
  - name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  - name: fedora
    flatpakrepo_url: oci+https://registry.fedoraproject.org

flatpak_remotes_manual_default:
  - name: knopki-bat
    flatpakrepo_url: https://knopki.github.com/bat-flatpak
    gpg_verify: no
    method: system

flatpaks_default:
  - { name: com.github.sharkdp.Bat, remote: knopki-bat }
