---
ssh_sk_pub_key: "{{ lookup('passwordstore','keys/ssh_knopki subkey=public') }}"
timezone: "Europe/Moscow"
system_locale: "en_US.UTF-8"
chrony_ntp_servers:
  - "0.ru.pool.ntp.org"
  - "1.ru.pool.ntp.org"
  - "2.ru.pool.ntp.org"
  - "3.ru.pool.ntp.org"
