---
# tasks file for locale
- include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - locale

- include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"
  tags:
    - locale

- include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Ubuntu"
  tags:
    - locale

