---
- name: Create target directory
  file:
    path: "{{ nerd_hack_install_path }}"
    state: directory
  tags: fonts

- name: Get file status of Nerd Font
  stat:
    path: "{{ nerd_hack_check_path }}"
  register: filestat
  when: install_nerd_hack
  tags: fonts

- name: Download and extract fonts
  unarchive:
    src: "{{ nerd_hack_url }}"
    dest: "{{ nerd_hack_install_path }}"
    remote_src: yes
  when: not filestat.stat.exists
  tags: fonts
