---
ansible_user: root
ansible_host: mir3g.lan

root_password: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/root') }}"

cjdns_private_key: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=private') }}"
cjdns_public_key: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=public') }}"
cjdns_ipv6: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=ipv6') }}"
cjdns_admin_password: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=admin_password') }}"
cjdns_authorizedPasswords:
  default-login: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=authorized_password_default_login') }}"
  private: "{{ lookup('passwordstore', 'devices/mir3g.1984.run/cjdns subkey=authorized_password_private') }}"

cjdns_udp_peers_self: []

cjdns_udp_peers:
  - "{{ cjdns_udp_peers_common|difference(cjdns_udp_peers_self) }}"
  #
  # Russia
  # Moscow
  - peerName: h.ihc.cupivan.ru
    address: 185.87.193.205
    address_type: ipv4
    port: 18842
    publicKey: 7h898y2xdhtm9xgng7f97umx9wfjhkxfx2wkxw89mrq2y6k954d0.k
    password: public
    ipv6: fc9b:499a:dd7a:92a:7b3e:be3a:32fc:53dc

  #
  # Ukraine
  #
  # Kiev
  - peerName: ic.hellomouse.cf
    address: 185.140.54.19
    address_type: ipv4
    port: 35907
    contact: iczero4@gmail.com
    gpg: "613CE9DA0E9A3F70EC97760E4BAC4EBB8461FC7E"
    publicKey: gtbfndu2tvfbwuydm7v0kpnqpgcburtymhz3ph9kfrjg4n8bh3j0.k
    login: public
    password: fwlmbx2f3udkd0ymknq4pwwgu2bjklx

  #
  # Latvia
  #
  - peerName: borg-vilnius
    address: 185.25.48.153
    address_type: ipv4
    port: 13109
    publicKey: pkq30hrl9zyzwn03u6lchh20crfgq46m1dfb5zwfhpx3c6v2l420.k
    password: public

  #
  # Norwegia
  #
  - peerName: hyperboria.hackeriet.no
    address: 185.35.202.206
    address_type: ipv4
    port: 21024
    publicKey: ny7v0951b703j4t2n4pyz474nny46wvbtq46x7hc8r2jql40dmr0.k
    password: tj0vkzk9rgub9888h3tf9gtm712tkuc
