---
uci_luci:
  - command: set
    key: luci.main
    type: core
    value:
      lang: auto
      mediaurlbase: "/luci-static/bootstrap"
      resourcebase: "/luci-static/resources"
  - command: set
    key: luci.flash_keep
    type: extern
    value:
      uci: "/etc/config/"
      dropbear: "/etc/dropbear/"
      openvpn: "/etc/openvpn/"
      passwd: "/etc/passwd"
      opkg: "/etc/opkg.conf"
      firewall: "/etc/firewall.user"
      uploads: "/lib/uci/upload/"
  - command: set
    key: luci.sauth
    type: internal
    value:
      sessionpath: "/tmp/luci-sessions"
      sessiontime: "3600"
  - command: set
    key: luci.ccache
    type: internal
    value:
      enable: "1"
  - command: set
    key: luci.themes
    type: internal
    value:
      Bootstrap: "/luci-static/bootstrap"
  - command: set
    key: luci.apply
    type: internal
    value:
      rollback: "30"
      holdoff: "4"
      timeout: "5"
      display: "1.5"
  - command: set
    key: luci.diag
    type: internal
    value:
      dns: "lede-project.org"
      ping: "lede-project.org"
      route: "lede-project.org"
