---
uci_etherwake:
  - command: set
    key: etherwake.etherwake
    type: setup
    value:
      pathes: "/usr/bin/etherwake /usr/bin/ether-wake"
      sudo: "off"
      broadcast: "off"
      interface: "br-lan"
  # - command: set
  #   key: etherwake.@target[0]
  #   value:
  #     name: example
  #     mac: "11:22:33:44:55:66"
  #     password: "sdfasdf"
  #     wakeonboot: "off"
