---
# Set autoupgrade option
- name: Set autoupgrade option
  when: atomic_host_autoupgrade is defined
    and atomic_host_autoupgrade == 'check'
  ini_file:
    path: /etc/rpm-ostreed.conf
    section: Daemon
    option: AutomaticUpdatePolicy
    value: "{{ atomic_host_autoupgrade }}"
    state: present
  notify:
    - rpm-ostreed restart
  tags: rpm-ostree-upgrade

- name: Set autoupgrade option
  when: atomic_host_autoupgrade is not defined
    or atomic_host_autoupgrade == 'none'
  ini_file:
    path: /etc/rpm-ostreed.conf
    section: Daemon
    option: AutomaticUpdatePolicy
    value: none
    state: present
  notify:
    - rpm-ostreed restart
  tags: rpm-ostree-upgrade

# Create ostree remote
- when: atomic_host_remote_name is defined and atomic_host_remote_url is defined and atomic_host_remote_gpg_verify is defined
  block:
  - name: Create ostree remote config
    ini_file:
      path: "/etc/ostree/remotes.d/{{ atomic_host_remote_name }}.conf"
      section: "remote \"{{ atomic_host_remote_name }}\""
      option: url
      value: "{{ atomic_host_remote_url }}"
    tags: rpm-ostree-upgrade

  - name: Create ostree remote config
    ini_file:
      path: "/etc/ostree/remotes.d/{{ atomic_host_remote_name }}.conf"
      section: "remote \"{{ atomic_host_remote_name }}\""
      option: gpg-verify
      value: "{{ atomic_host_remote_gpg_verify }}"
    tags: rpm-ostree-upgrade

# Gather facts
- name: Gather facts about ostree deployment
  command: rpm-ostree status --json
  register: rpmostree_status_raw
  changed_when: false
  check_mode: no
  tags: rpm-ostree-upgrade

- name: Set fact about ostree deployment
  set_fact: rpmostree_status={{ (rpmostree_status_raw.stdout | from_json).deployments | selectattr("booted","equalto",true) | join("")}}
  tags: rpm-ostree-upgrade
- name: Set fact about ostree desired ref
  set_fact: atomic_host_full_desired_ref="{{ atomic_host_remote_name }}:{{ atomic_host_desired_ref }}"
  when: atomic_host_remote_name is defined and atomic_host_desired_ref is defined
  tags: rpm-ostree-upgrade

# Rebase
- when: atomic_host_full_desired_ref is defined
  tags: rpm-ostree-upgrade
  block:
  - name: Rebase atomic host
    when: rpmostree_status.origin != atomic_host_full_desired_ref
    command: "rpm-ostree rebase {{ atomic_host_full_desired_ref }}"
    tags: rpm-ostree-upgrade

  - when: rpmostree_status.origin != atomic_host_full_desired_ref
    fail: msg="Please reboot {{ inventory_hostname }} to complete rebase"
    tags: rpm-ostree-upgrade

# Upgrade
- when: atomic_host_desired_version is defined
  tags: rpm-ostree-upgrade
  block:
  - name: Upgrade Atomic Host
    when: atomic_host_desired_version != rpmostree_status.version
    atomic_host:
      revision: "{{ atomic_host_desired_version }}"
    tags: rpm-ostree-upgrade

  - when: atomic_host_desired_version != rpmostree_status.version
    fail: msg="Please reboot {{ inventory_hostname }} to complete upgrade"
    tags: rpm-ostree-upgrade
