---
# Set autoupgrade option
- name: Set autoupgrade option
  when: rpm_ostree_autoupgrade is defined
    and rpm_ostree_autoupgrade == 'check'
  ini_file:
    path: /etc/rpm-ostreed.conf
    section: Daemon
    option: AutomaticUpdatePolicy
    value: "{{ rpm_ostree_autoupgrade }}"
    state: present
  notify:
    - rpm-ostreed restart
  tags: rpm-ostree-upgrade

- name: Set autoupgrade option
  when: rpm_ostree_autoupgrade is not defined
    or rpm_ostree_autoupgrade == 'none'
  ini_file:
    path: /etc/rpm-ostreed.conf
    section: Daemon
    option: AutomaticUpdatePolicy
    value: none
    state: present
  notify:
    - rpm-ostreed restart
  tags: rpm-ostree-upgrade

# Create ostree remote
- when: rpm_ostree_remote_name is defined and rpm_ostree_remote_url is defined
  block:
  - name: Create ostree remote config
    ini_file:
      path: "/etc/ostree/remotes.d/{{ rpm_ostree_remote_name }}.conf"
      section: "remote \"{{ rpm_ostree_remote_name }}\""
      option: url
      value: "{{ rpm_ostree_remote_url }}"
    tags: rpm-ostree-upgrade

  - name: Create ostree remote config
    ini_file:
      path: "/etc/ostree/remotes.d/{{ rpm_ostree_remote_name }}.conf"
      section: "remote \"{{ rpm_ostree_remote_name }}\""
      option: gpg-verify
      value: "{{ rpm_ostree_remote_gpg_verify|default('true') }}"
    tags: rpm-ostree-upgrade

  - name: Create ostree remote config
    ini_file:
      path: "/etc/ostree/remotes.d/{{ rpm_ostree_remote_name }}.conf"
      section: "remote \"{{ rpm_ostree_remote_name }}\""
      option: gpgkeypath
      value: "{{ rpm_ostree_remote_gpgkeypath }}"
    tags: rpm-ostree-upgrade
    when: rpm_ostree_remote_gpgkeypath is defined

# Gather facts
- name: Gather facts about ostree deployment
  command: rpm-ostree status --json
  register: rpmostree_status_raw
  changed_when: false
  check_mode: no
  tags: rpm-ostree-upgrade

- name: Set fact about ostree deployment
  set_fact: rpmostree_status={{ (rpmostree_status_raw.stdout | from_json).deployments | selectattr("booted","equalto",true) | join("")}}
  tags: rpm-ostree-upgrade
- name: Set fact about ostree desired ref
  set_fact: rpm_ostree_full_desired_ref="{{ rpm_ostree_remote_name }}:{{ rpm_ostree_desired_ref }}"
  when: rpm_ostree_remote_name is defined and rpm_ostree_desired_ref is defined
  tags: rpm-ostree-upgrade

# Rebase
- when: rpm_ostree_full_desired_ref is defined
  tags: rpm-ostree-upgrade
  block:
  - name: Rebase atomic host
    when: rpmostree_status.origin != rpm_ostree_full_desired_ref
    command: "rpm-ostree rebase {{ rpm_ostree_full_desired_ref }}"
    tags: rpm-ostree-upgrade

  - when: rpmostree_status.origin != rpm_ostree_full_desired_ref
    fail: msg="Please reboot {{ inventory_hostname }} to complete rebase"
    tags: rpm-ostree-upgrade

# Upgrade
- when: rpm_ostree_desired_version is defined
  tags: rpm-ostree-upgrade
  block:
  - name: Upgrade Atomic Host
    when: rpm_ostree_desired_version != rpmostree_status.version
    atomic_host:
      revision: "{{ rpm_ostree_desired_version }}"
    tags: rpm-ostree-upgrade

  - when: rpm_ostree_desired_version != rpmostree_status.version
    fail: msg="Please reboot {{ inventory_hostname }} to complete upgrade"
    tags: rpm-ostree-upgrade
